In [9]:
import numpy as np
#Lets define a few of the constants and variables
A = 10.25 #in^2
I = 570 #in^4
E = 31e6 #lb/in
w = 2000 #lbf/ft
p1 = 300
p2 = 500
L = 1 #Length of Element
print(3**2/2)

#This is our inital load matrix equations taken from table D-1
F = np.array([(-w-L/2), ((-w*L**2)/12),
              (-w*L**2/2), (-w*L/2 + 13*w*L/32),
              (-p1/2), (-p1*L/8),     
              (-p1/2-p2), (p1*L/8),
              ]).reshape(8,1)

# F = np.array([1,1,1,1,1,1,1,1]).reshape(8,1)
print(F)
def genK(j,i1,i2,L,A,E,I): #(element number, node1, node2, element length, phi) 
    big_k = np.zeros((10,10)) #size of the global matrix before we add them together
    const = E*I/L**3 #the constant scalar that goes along with stiffness matrix
    #kj matrix is the given stiffness matrix for a beam element
    kj = np.array([  
        [12,   6*L,    -12,   6*L],
        [6*L,  4*L**2, -6*L,  2*L**2],
        [-12,  -6*L,    12,   -6*L],
        [6*L,  2*L**2, -6*L,  4*L**2],
        ])
        
    # print("transfomration matrix off theta")
    # print(transform)
    # print("Displacement for element",+j)
    # ds = np.array([i1,i1,i2,i2]).reshape(4,1)
    # k_small = np.round((const * transform), 1)
    # print(kj, "<--- Global stiffness values in small matrix form for element", +j)

    # #This portion of the code indexes the small K matricies and aranges them respect to the big global K matrix
    # #indexing starts at 0 thus we need to take into consideration for the indexing
    rows = [2 * i1 - 2, 2 * i1 - 1, 2 * i2 - 2, 2 * i2 - 1] 
    cols = rows #Symetrical
    #Arranges small K matrix into the big K matrix for addition later
    big_k[np.ix_(rows, cols)] += kj
    big_k = np.round((big_k), 3)
    print(big_k)

    return(big_k)

k1 = genK(1,1,2,L,A,E,I)
k2 = genK(2,2,3,L,A,E,I)
k3 = genK(3,3,4,L,A,E,I)
k4 = genK(4,4,5,L,A,E,I)

4.5
[[-2000.5       ]
 [ -166.66666667]
 [-1000.        ]
 [ -187.5       ]
 [ -150.        ]
 [  -37.5       ]
 [ -650.        ]
 [   37.5       ]]
[[ 12.   6. -12.   6.   0.   0.   0.   0.   0.   0.]
 [  6.   4.  -6.   2.   0.   0.   0.   0.   0.   0.]
 [-12.  -6.  12.  -6.   0.   0.   0.   0.   0.   0.]
 [  6.   2.  -6.   4.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]]
[[  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.  12.   6. -12.   6.   0.   0.   0.   0.]
 [  0.   0.   6.   4.  -6.   2.   0.   0.   0.   0.]
 [  0.   0. -12.  -6.  12.  -6.   0.   0.   0.   0.]
 [  0.   0.   6.   2.  -6.   4.   0.   0.   0.   0.]
 [